export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST";

export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS";

export const CREATE_ORDER_FAIL="CREATE_ORDER_FAIL";



export const MYORDER_ORDER_REQUEST="MYORDER_ORDER_REQUEST";

export const MYORDER_ORDER_SUCCESS="MYORDER_ORDER_SUCCESS";

export const MYORDER_ORDER_FAIL="MYORDER_ORDER_FAIL";



export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";

export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";

export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";


export const ALL_ORDER_REQUEST="ALL_ORDER_REQUEST";

export const ALL_ORDER_SUCCESS="ALL_ORDER_SUCCESS";

export const ALL_ORDER_FAIL="ALL_ORDER_FAIL";


export const UPDATE_ORDER_REQUEST="UPDATE_ORDER_REQUEST";

export const UPDATE_ORDER_SUCCESS="UPDATE_ORDER_SUCCESS";

export const UPDATE_ORDER_FAIL="UPDATE_ORDER_FAIL";

export const UPDATE_ORDER_RESET="UPDATE_ORDER_RESET";



export const DELETE_ORDER_REQUEST="DELETE_ORDER_REQUEST";

export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS";

export const DELETE_ORDER_FAIL="DELETE_ORDER_FAIL";

export const DELETE_ORDER_RESET="DELETE_ORDER_RESET";










export const CLEAR_ERRORS="CLEAR_ERRORS";